# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/constraints/Basys3_Master.xdc

# IP: E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/ip/xadc_wiz_0_1/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0}]
