# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Basys3-master/Basys3-master/Projects/XADC_Demo/proj/XADC_Demo.cache/wt [current_project]
set_property parent.project_path E:/Basys3-master/Basys3-master/Projects/XADC_Demo/proj/XADC_Demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths E:/Basys3-master/Basys3-master/Projects/XADC_Demo/repo [current_project]
read_ip E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/ip/xadc_wiz_0_1/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/ip/xadc_wiz_0_1/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/ip/xadc_wiz_0_1/xadc_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/ip/xadc_wiz_0_1/xadc_wiz_0.dcp]
set_property is_locked true [get_files E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/ip/xadc_wiz_0_1/xadc_wiz_0.xci]

read_verilog -library xil_defaultlib {
  E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/hdl/sevensegdecoder.v
  E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/hdl/segClkDevider.v
  E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/hdl/mux4_4bus.v
  E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/hdl/decoder3_8.v
  E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/hdl/counter3bit.v
  E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/hdl/DigitToSeg.v
  E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/hdl/XADCdemo.v
}
read_xdc E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/constraints/Basys3_Master.xdc
set_property used_in_implementation false [get_files E:/Basys3-master/Basys3-master/Projects/XADC_Demo/src/constraints/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file XADCdemo.hwdef }
synth_design -top XADCdemo -part xc7a35tcpg236-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint -noxdef XADCdemo.dcp
catch { report_utilization -file XADCdemo_utilization_synth.rpt -pb XADCdemo_utilization_synth.pb }
