# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/ZYNQ_prj/DigitalCircuit/XADC/src/ip/xadc_wiz_0_1/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ZYNQ_prj/DigitalCircuit/XADC/src/ip/xadc_wiz_0_1/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: h:/ZYNQ_prj/DigitalCircuit/XADC/src/ip/xadc_wiz_0_1/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: H:/ZYNQ_prj/DigitalCircuit/XADC/src/ip/xadc_wiz_0_1/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ZYNQ_prj/DigitalCircuit/XADC/src/ip/xadc_wiz_0_1/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: h:/ZYNQ_prj/DigitalCircuit/XADC/src/ip/xadc_wiz_0_1/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
