# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/uart/uart/uart.cache/wt [current_project]
set_property parent.project_path E:/uart/uart/uart.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/uart/uart/uart.srcs/sources_1/new/speed_select_rx.v
  E:/uart/uart/uart.srcs/sources_1/new/my_uart_tx.v
  E:/uart/uart/uart.srcs/sources_1/new/my_uart_rx.v
  E:/uart/uart/uart.srcs/sources_1/new/uart_top.v
}
read_xdc E:/uart/uart/uart.srcs/constrs_1/new/uart.xdc
set_property used_in_implementation false [get_files E:/uart/uart/uart.srcs/constrs_1/new/uart.xdc]

catch { write_hwdef -file my_uart_top.hwdef }
synth_design -top my_uart_top -part xc7a35tcpg236-1
write_checkpoint -noxdef my_uart_top.dcp
catch { report_utilization -file my_uart_top_utilization_synth.rpt -pb my_uart_top_utilization_synth.pb }
